### PR TITLE
test(integration): requires space id as an environment variable

### PR DESCRIPTION
**Pull request by boblington**

### CODE REVIEW

**Comment by boblington** [comment]
@deluan did you remove the designated space for integration test?

**Comment by deluan** [comment]
@boblington Yes I did, sorry. But I created a new one, and the tests are still not passing. Can you please check?

**Comment by boblington** [comment]
@deluan looks like Travis's env variable for contentful space id hasn't been updated to the new one you created? it's still using `qnlga9yp8glg`

**Comment by boblington** [comment]
@deluan I *THINK* it's stable now

**Pull request merged**
