### PR TITLE
Allow persistent default values for space-id & env-id using environment vars

### PR DESCRIPTION
**Pull request by void--**
Similar to how the access token can already be specified via environment variable, this PR allows a user who will often be working in the same contentful space / environment to specify these defaults using env vars.

### CODE REVIEW

**Comment by deluan** [comment]
Thanks for the contribution!

**Comment by void--** [comment]
my pleasure :D

**Comment by deluan** [comment]
Just noticed: Can you please add the new options to the README?

**Comment by void--** [comment]
Ah good call, on it

**Pull request merged**
