### PR TITLE
⬆️ Update contentful dependencies

### PR DESCRIPTION
**Pull request by OriginalEXE**
Hello,

This PR updates the contentful dependencies (mainly `contentful-migration`). There was a breaking change in v3.0.0 so I adjusted `run.js` to take that into account.

Let me know if anything else is needed, all tests are passing.

### CODE REVIEW

**Comment by deluan** [comment]
Hey @OriginalEXE , thanks for the PR! I found an issue with flakiness in the integration tests, but don't want to commit before merging this, so can you please fix the conflicts?

**Comment by OriginalEXE** [comment]
Hey @deluan, which conflicts are we talking about> I thought I have already resolved them 🤔  Don't see anything in the GitHub UI

**Comment by michielmetcake** [comment]
Probably needs a version bump?

**Comment by deluan** [comment]
These conflicts: 
Screen Shot 2021-03-22 at 9 55 32 AM

But looks like I can Squash and merge. Will try that.

**Comment by deluan** [comment]
Great! Will fix the flakiness and hopefully we will be able to release a new version tonight! Thanks for this!

**Comment by OriginalEXE** [comment]
Ah sorry, did not see that, showed it as merge-able to me 🤷🏻 

Thanks for taking care of it!

**Pull request merged**
