### PR TITLE
Update contentful-migration and contentful-management

### PR DESCRIPTION
**Pull request by akeemattelus**

### CODE REVIEW

**Comment by deluan** [comment]
Hey, thanks for this. Were you able to run the integration tests? I'm trying in my local but they don't pass:
```
1) Integration Test @integration
       "before all" hook: createTestEnvironment in "Integration Test @integration":
     NotFound: {
  "status": 404,
  "statusText": "Not Found",
  "message": "The resource could not be found.",
  "details": {
    "type": "Environment",
    "id": "test-20210118040559",
    "space": "9tar41poucew"
  },
  "request": {
    "url": "locales",
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "Content-Type": "application/vnd.contentful.management.v1+json",
      "X-Contentful-User-Agent": "sdk contentful-management.js/6.3.2; platform node.js/v14.13.1; os macOS/19.6.0;",
      "Authorization": "Bearer ...SmX04",
      "user-agent": "node.js/v14.13.1",
      "Accept-Encoding": "gzip"
    },
    "method": "get"
  },
  "requestId": "809f5911d24b3040a7e3d4bf0237bab2"
}
```

**Comment by akeemattelus** [comment]
Yes,

I got similar errors until I updated the management token and space. I've set it to a space we use on our team and I got this: 
image

This is from the pre-commit hook and `npm test` returns the same output.
To be honest the tests ran super fast not sure if they are being ran correctly. I will check on that.

**Comment by deluan** [comment]
To run the all tests (including the integration tests), you need to run `npm run test:ci`

**Comment by deluan** [comment]
This was fixed in #196

**Pull request closed without merging**
